script:
  - docker pull geonetwork:3.6.0
  - docker run --net=host -d --name db arminc/clair-db
  - docker run --net=host --add-host postgres:127.0.0.1 -d --name clair arminc/clair-local-scan:latest
  - wget https://github.com/optiopay/klar/releases/download/v2.4.0/klar-2.4.0-linux-amd64
  - mv klar-2.4.0-linux-amd64 klar
  - chmod +x klar
  - sleep 30 # wait for clair db to start
  - CLAIR_ADDR=0.0.0.0 CLAIR_THRESHOLD=10 ./klar geonetwork:3.6.0
